apiVersion: v1
kind: Service
metadata:
  name: testapp-svc-0
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: testapp-svc-0
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: testapp-svc-0
  name: testapp-svc-0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp-svc-0
  template:
    metadata:
      labels:
        app: testapp-svc-0
    spec:
      containers:
      - image: ratnadeepb/testapp:jaeger
        imagePullPolicy: Always
        name: testapp-svc-0
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1500m
            memory: 100Mi
          requests:
            cpu: 1000m
            memory: 50Mi
